Adding "restart: always" to ReadMe
jc21/nginx-proxy-manager pull request #1155
Opened 2021-06-06 17:18 UTC by ChrisTracy

Adding "restart: always" to ReadMe. I had a hard time figuring out why once of my NPM containers would not start on reboot while the rest of them would. It turns out I copied two of my compose files from the official site and one of the from the GitHub repo.

2021-06-06 21:46 UTC, jc21 requested changes
I think it would be safer to use "unless-stopped" instead of always. A reboot would still bring it back online but those who want it to stay stopped would get that too

2021-06-06 23:00 UTC, jc21 commented
This is an automated message from CI:

Docker Image for build 2 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1155`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

2021-06-07 14:39 UTC, ChrisTracy reviewed
Changed to "unless-stopped"

2021-06-07 14:41 UTC, ChrisTracy commented
That is a good point, I went ahead and changed it. Just FYI the documentation on the site has "always" in it. I am not sure if that is intentional for production use only.

2021-06-07 15:16 UTC, jc21 commented
This is an automated message from CI:

Docker Image for build 3 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1155`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

2021-06-07 22:44 UTC, jc21 commented
yep you're right. I'll change the docs as well.

2021-06-07 22:45 UTC, jc21 approved these changes

2021-06-07 22:45 UTC, merged